### ISSUE TITLE
Please change the package name

### ISSUE THREAD

**Issue by hosamaly** [dev-ahmadbilal/islam.js#5]
Currently, the package is called `islam`, as if it claims to be representative of the religion.

We are all humans. We make mistakes. None of us represents the religion. We are associated with it, and we may be knowledgeable about it, and we may have done our best to use authentic sources. But we still cannot claim to represent Islam. Our work may be faulty.

This package is definitely useful and it's clear that a lot of effort went into it, and I thank you for that. But please change the package name. Call it `islamics` if you wish, or any other name, but please refrain from names that may suggest that this package is the only true source of information.

**Comment by m-elkady** [comment]
I recommend @hosamaly suggestion and suggest more names like `islamic-lib` or nay other names that represent the package not Islam 😊

**Comment by dev-ahmadbilal** [comment]
Thank you for your feedback and for raising this important concern.

I completely understand your point, and I want to clarify that I never intended to claim that this package is the definitive or only true representation of Islam. As a human-made project, it is naturally subject to errors and imperfections.

To address your concern, I have updated the documentation to include a disclaimer explicitly stating that this package is not an authoritative source on Islam and may contain mistakes. The package was created with the aim of providing easy access to Islamic resources, but users should always consult authentic scholars and verified sources for religious guidance.

Regarding the name change, I appreciate your suggestion; however, at this time, I am not considering changing the name. The current name, "islam.js," was chosen to convey the general purpose of the package, and I believe it aligns with that intent.

Thank you again for your input and understanding. I hope this change clarifies the intent behind the package.
